// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PMA.Api.Entites;

#nullable disable

namespace PMA.Api.Migrations
{
    [DbContext(typeof(PmaDbContext))]
    partial class PmaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PMA.Api.Entites.ActePma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("LIBELLE");

                    b.Property<string>("Observation")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBSERVATION");

                    b.Property<int>("PatientId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIENTID");

                    b.Property<string>("StatutRealisation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("STATUTREALISATION");

                    b.Property<string>("TypeActe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TYPEACTE");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("ACTES_PMA", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.AlerteCryo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Acquittee")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("ACQUITTEE");

                    b.Property<DateTime>("DateAlerte")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATEALERTE");

                    b.Property<string>("Equipement")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EQUIPEMENT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("MESSAGE");

                    b.Property<string>("Severite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("SEVERITE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.ToTable("ALERTES_CRYO", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.Bonbonne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CODE");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("COULEUR");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TEMPERATURE");

                    b.Property<string>("TypeStockage")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TYPESTOCKAGE");

                    b.HasKey("Id");

                    b.ToTable("BONBONNES", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.Canister", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonbonneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BONBONNEID");

                    b.Property<int>("Numero")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NUMERO");

                    b.HasKey("Id");

                    b.HasIndex("BonbonneId");

                    b.ToTable("CANISTERS", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.CapteurTemperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonbonneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BONBONNEID");

                    b.Property<DateTime>("DerniereMaj")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DERNIEREMAJ");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("NOM");

                    b.Property<double>("SeuilAlerte")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("SEUILALERTE");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUT");

                    b.Property<double>("TemperatureActuelle")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("TEMPERATUREACTUELLE");

                    b.Property<double>("TemperatureCible")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("TEMPERATURECIBLE");

                    b.HasKey("Id");

                    b.HasIndex("BonbonneId");

                    b.ToTable("CAPTEURS_TEMPERATURE", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.Consentement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CinFemmePath")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("CINFEMMEPATH");

                    b.Property<string>("CinHommePath")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("CINHOMMEPATH");

                    b.Property<string>("ContratMariagePath")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("CONTRATMARIAGEPATH");

                    b.Property<DateTime>("DateSignature")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATESIGNATURE");

                    b.Property<int>("PatientId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIENTID");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("PHOTOPATH");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("CONSENTEMENTS", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.CycleEtapeHistorique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclePmaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CYCLEPMAID");

                    b.Property<DateTime>("DateEtape")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATEETAPE");

                    b.Property<string>("Etape")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ETAPE");

                    b.Property<string>("Observation")
                        .HasMaxLength(2000)
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBSERVATION");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUT");

                    b.Property<int?>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.HasIndex("CyclePmaId");

                    b.HasIndex("UserId");

                    b.ToTable("CYCLES_ETAPES_HISTORIQUE", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.CyclePma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATEDEBUT");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATEFIN");

                    b.Property<DateTime>("DerniereMiseAJour")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DERNIEREMISEAJOUR");

                    b.Property<string>("EtapeCourante")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("ETAPECOURANTE");

                    b.Property<int>("PatientId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIENTID");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("PHASE");

                    b.Property<int?>("ProtocoleId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PROTOCOLEID");

                    b.Property<string>("ResultatTestGrossesse")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("ResultatTestSigneLe")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("ResultatTestSignePar")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("StatutCycle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUTCYCLE");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ProtocoleId");

                    b.ToTable("CYCLES_PMA", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.ElementBiologique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeBarre")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATECREATION");

                    b.Property<string>("NumeroTube")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NUMEROTUBE");

                    b.Property<int>("PatientId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIENTID");

                    b.Property<string>("TypeElement")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TYPEELEMENT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("ELEMENTS_BIOLOGIQUES", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.HistoriqueTemperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapteurTemperatureId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CAPTEURTEMPERATUREID");

                    b.Property<DateTime>("DateMesure")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATEMESURE");

                    b.Property<double>("Valeur")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VALEUR");

                    b.HasKey("Id");

                    b.HasIndex("CapteurTemperatureId");

                    b.ToTable("HISTORIQUES_TEMPERATURE", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.MaintenancePreventive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DerniereExecution")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DERNIEREEXECUTION");

                    b.Property<string>("Equipement")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("EQUIPEMENT");

                    b.Property<int>("FrequenceJours")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("FREQUENCEJOURS");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("NOTES");

                    b.Property<DateTime>("ProchaineExecution")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PROCHAINEEXECUTION");

                    b.Property<string>("Responsable")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("RESPONSABLE");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUT");

                    b.Property<string>("TypeEquipement")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TYPEEQUIPEMENT");

                    b.Property<string>("TypeMaintenance")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("TYPEMAINTENANCE");

                    b.HasKey("Id");

                    b.ToTable("MAINTENANCES_PREVENTIVES", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.NiveauAzote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BonbonneId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("BONBONNEID");

                    b.Property<double>("CapaciteLitres")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("CAPACITELITRES");

                    b.Property<DateTime>("DernierRemplissage")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DERNIERREMPLISSAGE");

                    b.Property<double>("NiveauPourcentage")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("NIVEAUPOURCENTAGE");

                    b.Property<DateTime>("ProchainRemplissage")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("PROCHAINREMPLISSAGE");

                    b.Property<double>("SeuilAlerte")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("SEUILALERTE");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("STATUT");

                    b.Property<double>("VolumeLitres")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("VOLUMELITRES");

                    b.HasKey("Id");

                    b.HasIndex("BonbonneId");

                    b.ToTable("NIVEAUX_AZOTE", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.PailleTube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanisterId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CANISTERID");

                    b.Property<string>("CodeBarre")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("CODEBARRE");

                    b.Property<string>("CouleurVisotube")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("CyclePmaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CYCLEPMAID");

                    b.Property<int?>("PatientId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Position")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("POSITION");

                    b.Property<string>("TypeContenu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TYPECONTENU");

                    b.HasKey("Id");

                    b.HasIndex("CanisterId");

                    b.HasIndex("CodeBarre")
                        .IsUnique();

                    b.HasIndex("CyclePmaId");

                    b.HasIndex("PatientId");

                    b.ToTable("PAILLES_TUBES", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("ADRESSE");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATENAISSANCE");

                    b.Property<DateTime?>("FemmeDateNaissance")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("FEMMEDATENAISSANCE");

                    b.Property<string>("FemmeNom")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FEMMENOM");

                    b.Property<string>("FemmePrenom")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FEMMEPRENOM");

                    b.Property<string>("ImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("IMAGEPATH");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM");

                    b.Property<string>("NumDossier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NUMDOSSIER");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PRENOM");

                    b.Property<string>("Telephone")
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TELEPHONE");

                    b.Property<string>("TypeActePma")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TYPEACTEPMA");

                    b.Property<string>("TypeDossier")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("TYPEDOSSIER");

                    b.HasKey("Id");

                    b.HasIndex("NumDossier")
                        .IsUnique();

                    b.ToTable("PATIENTS", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("LIBELLE");

                    b.HasKey("Id");

                    b.ToTable("PROFILES", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.Protocole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id");

                    b.ToTable("PROTOCOLS", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.RealisationActe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActePmaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ACTEPMAID");

                    b.Property<DateTime>("DateRealisation")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATEREALISATION");

                    b.Property<string>("Observation")
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("OBSERVATION");

                    b.Property<string>("Resultat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESULTAT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("STATUT");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("USERID");

                    b.HasKey("Id");

                    b.HasIndex("ActePmaId");

                    b.HasIndex("UserId");

                    b.ToTable("REALISATIONS_ACTES", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.RendezVous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateHeure")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATEHEURE");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MOTIF");

                    b.Property<int>("PatientId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PATIENTID");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("STATUT");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("RENDEZ_VOUS", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("IDENTIFIANT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOM");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("PASSWORDHASH");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("PRENOM");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("PROFILEID");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("TELEPHONE");

                    b.HasKey("Id");

                    b.HasIndex("Identifiant")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("PMA.Api.Entites.ActePma", b =>
                {
                    b.HasOne("PMA.Api.Entites.Patient", "Patient")
                        .WithMany("ActesPma")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PMA.Api.Entites.Canister", b =>
                {
                    b.HasOne("PMA.Api.Entites.Bonbonne", "Bonbonne")
                        .WithMany("Canisters")
                        .HasForeignKey("BonbonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bonbonne");
                });

            modelBuilder.Entity("PMA.Api.Entites.CapteurTemperature", b =>
                {
                    b.HasOne("PMA.Api.Entites.Bonbonne", "Bonbonne")
                        .WithMany()
                        .HasForeignKey("BonbonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bonbonne");
                });

            modelBuilder.Entity("PMA.Api.Entites.Consentement", b =>
                {
                    b.HasOne("PMA.Api.Entites.Patient", "Patient")
                        .WithMany("Consentements")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PMA.Api.Entites.CycleEtapeHistorique", b =>
                {
                    b.HasOne("PMA.Api.Entites.CyclePma", "CyclePma")
                        .WithMany("EtapesHistorique")
                        .HasForeignKey("CyclePmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Api.Entites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CyclePma");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PMA.Api.Entites.CyclePma", b =>
                {
                    b.HasOne("PMA.Api.Entites.Patient", "Patient")
                        .WithMany("CyclesPma")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Api.Entites.Protocole", "Protocole")
                        .WithMany("CyclesPma")
                        .HasForeignKey("ProtocoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient");

                    b.Navigation("Protocole");
                });

            modelBuilder.Entity("PMA.Api.Entites.ElementBiologique", b =>
                {
                    b.HasOne("PMA.Api.Entites.Patient", "Patient")
                        .WithMany("ElementsBiologiques")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PMA.Api.Entites.HistoriqueTemperature", b =>
                {
                    b.HasOne("PMA.Api.Entites.CapteurTemperature", "CapteurTemperature")
                        .WithMany("Historiques")
                        .HasForeignKey("CapteurTemperatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapteurTemperature");
                });

            modelBuilder.Entity("PMA.Api.Entites.NiveauAzote", b =>
                {
                    b.HasOne("PMA.Api.Entites.Bonbonne", "Bonbonne")
                        .WithMany()
                        .HasForeignKey("BonbonneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bonbonne");
                });

            modelBuilder.Entity("PMA.Api.Entites.PailleTube", b =>
                {
                    b.HasOne("PMA.Api.Entites.Canister", "Canister")
                        .WithMany("PailleTubes")
                        .HasForeignKey("CanisterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PMA.Api.Entites.CyclePma", "CyclePma")
                        .WithMany("PailleTubes")
                        .HasForeignKey("CyclePmaId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PMA.Api.Entites.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("Canister");

                    b.Navigation("CyclePma");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PMA.Api.Entites.RealisationActe", b =>
                {
                    b.HasOne("PMA.Api.Entites.ActePma", "ActePma")
                        .WithMany("Realisations")
                        .HasForeignKey("ActePmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMA.Api.Entites.User", "User")
                        .WithMany("RealisationsActes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActePma");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PMA.Api.Entites.RendezVous", b =>
                {
                    b.HasOne("PMA.Api.Entites.Patient", "Patient")
                        .WithMany("RendezVous")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PMA.Api.Entites.User", b =>
                {
                    b.HasOne("PMA.Api.Entites.Profile", "Profile")
                        .WithMany("Users")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("PMA.Api.Entites.ActePma", b =>
                {
                    b.Navigation("Realisations");
                });

            modelBuilder.Entity("PMA.Api.Entites.Bonbonne", b =>
                {
                    b.Navigation("Canisters");
                });

            modelBuilder.Entity("PMA.Api.Entites.Canister", b =>
                {
                    b.Navigation("PailleTubes");
                });

            modelBuilder.Entity("PMA.Api.Entites.CapteurTemperature", b =>
                {
                    b.Navigation("Historiques");
                });

            modelBuilder.Entity("PMA.Api.Entites.CyclePma", b =>
                {
                    b.Navigation("EtapesHistorique");

                    b.Navigation("PailleTubes");
                });

            modelBuilder.Entity("PMA.Api.Entites.Patient", b =>
                {
                    b.Navigation("ActesPma");

                    b.Navigation("Consentements");

                    b.Navigation("CyclesPma");

                    b.Navigation("ElementsBiologiques");

                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("PMA.Api.Entites.Profile", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("PMA.Api.Entites.Protocole", b =>
                {
                    b.Navigation("CyclesPma");
                });

            modelBuilder.Entity("PMA.Api.Entites.User", b =>
                {
                    b.Navigation("RealisationsActes");
                });
#pragma warning restore 612, 618
        }
    }
}
